on:
  workflow_run:
    workflows: ["Pro"]
    types:
      - completed

jobs:
  publish_nuget:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Publish nuget package
    runs-on: ubuntu-latest
    environment: ${{ github.event.workflow_run.name }}

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}

      # - name: Publish to nuget
      #   run: dotnet nuget push packages/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

  publish_sample_site:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Publish sample site
    runs-on: ubuntu-latest
    environment: ${{ github.event.workflow_run.name }}

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
    
      # - name: 'Run Azure webapp deploy using publish profile credentials'
      #   uses: azure/webapps-deploy@v2
      #   with: 
      #     app-name: ${{ secrets.AZURE_WEBAPP_NAME }} # Replace with your app name
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_DEV_PUBLISH_PROFILE }} # Define secret variable in repository settings as per action documentation
      #     package: 'Sample.AspNetCore'