name: Run unit and ui tests, deploy samplesite 
on:
  workflow_run:
    workflows: ["Dev", "Uat"]
    types:
      - completed

env:
  dotnetVersion: |
    3.1.101
    5.x
    6.x

jobs:
  test-unit-ui:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.workflow_run.name }}

    steps:
      - name: "Get information about the origin 'CI' run"
        uses: potiuk/get-workflow-origin@v1_1
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
     
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
         # comma separated list of XML/JSON/YAML files in which tokens are to be substituted. Files names must be specified relative to the folder-path.
           files: 'Sample.AspNetCore/appsettings.json, Sample.AspNetCore/ngrok.yml, Sample.AspNetCore.SystemTests/appsettings.json'
        env:
          authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          Credentials.0.MerchantId: ${{ secrets.SWEDEN_MERCHANT_ID }}
          Credentials.0.Secret: ${{ secrets.SWEDEN_MERCHANT_SECRET }}
          Credentials.1.MerchantId: ${{ secrets.NORWAY_MERCHANT_ID }}
          Credentials.1.Secret: ${{ secrets.NORWAY_MERCHANT_SECRET }}
          Credentials.2.MerchantId: ${{ secrets.FINNISH_MERCHANT_ID }}
          Credentials.2.Secret: ${{ secrets.FINNISH_MERCHANT_SECRET }}
          MerchantSettings.PushUri: https://svea-webpay-sdk-001-${{ needs.variables.outputs.ENVIRONMENT }}.azurewebsites.net/api/svea/push/{checkout.order.uri}/?marketId={marketId}
          MerchantSettings.TermsUri: https://svea-webpay-sdk-001-${{ needs.variables.outputs.ENVIRONMENT }}.azurewebsites.net/terms
          MerchantSettings.CheckoutUri: https://svea-webpay-sdk-001-${{ needs.variables.outputs.ENVIRONMENT }}.azurewebsites.net/CheckOut/LoadPaymentMenu
          MerchantSettings.ConfirmationUri: https://svea-webpay-sdk-001-${{ needs.variables.outputs.ENVIRONMENT }}.azurewebsites.net/checkout/thankyou
          MerchantSettings.CheckoutValidationCallbackUri: https://svea-webpay-sdk-001-${{ needs.variables.outputs.ENVIRONMENT }}.azurewebsites.net/api/svea/validation/{checkout.order.uri}/?marketId={marketId}

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.dotnetVersion }}       

      - name: Run Unit Tests
        run: dotnet test Sdk.UnitTests/Svea.WebPay.SDK.Tests.dll
        env:
          Credentials:0:MerchantId: ${{ secrets.SWEDEN_MERCHANT_ID}}
          Credentials:0:Secret: ${{ secrets.SWEDEN_MERCHANT_SECRET }}
          Credentials:1:MerchantId: ${{ secrets.NORWAY_MERCHANT_ID}}
          Credentials:1:Secret: ${{ secrets.NORWAY_MERCHANT_SECRET }}
          Credentials:2:MerchantId: ${{ secrets.FINNISH_MERCHANT_ID }}
          Credentials:2:Secret: ${{ secrets.FINNISH_MERCHANT_SECRET }}

      - name: Setup ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          jar xvf ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          
      - name: Start ngrok
        run: ./ngrok start -config Sample.AspNetCore/ngrok.yml uitest${{ github.event.workflow_run.name }} &
                   
      - name: Start SDK Sample project
        working-directory: Sample.AspNetCore
        run:
            dotnet Sample.AspNetCore.dll &
        env:
          Credentials:0:MerchantId: ${{ secrets.SWEDEN_MERCHANT_ID}}
          Credentials:0:Secret: ${{ secrets.SWEDEN_MERCHANT_SECRET }}
          Credentials:1:MerchantId: ${{ secrets.NORWAY_MERCHANT_ID}}
          Credentials:1:Secret: ${{ secrets.NORWAY_MERCHANT_SECRET }}
          Credentials:2:MerchantId: ${{ secrets.FINNISH_MERCHANT_ID }}
          Credentials:2:Secret: ${{ secrets.FINNISH_MERCHANT_SECRET }}
          MerchantSettings:PushUri: https://uitest-${{ github.event.workflow_run.name }}-svea-webpay-sdk.eu.ngrok.io/api/svea/push/{checkout.order.uri}/?marketId={marketId}
          MerchantSettings:TermsUri: https://uitest-${{ github.event.workflow_run.name }}-svea-webpay-sdk.eu.ngrok.io/terms
          MerchantSettings:CheckoutUri: https://uitest-${{ github.event.workflow_run.name }}-svea-webpay-sdk.eu.ngrok.io/CheckOut/LoadPaymentMenu
          MerchantSettings:ConfirmationUri: https://uitest-${{ github.event.workflow_run.name }}-svea-webpay-sdk.eu.ngrok.io/checkout/thankyou
          MerchantSettings:CheckoutValidationCallbackUri: https://uitest-${{ github.event.workflow_run.name }}-svea-webpay-sdk.eu.ngrok.io/api/svea/validation/{checkout.order.uri}/?marketId={marketId}
      
      - name: Run SDK UI tests
        run: dotnet test Sample.AspNetCore.SystemTests/Sample.AspNetCore.SystemTests.dll
        env:
          Credentials:0:MerchantId: ${{ secrets.SWEDEN_MERCHANT_ID}}
          Credentials:0:Secret: ${{ secrets.SWEDEN_MERCHANT_SECRET }}
          Credentials:1:MerchantId: ${{ secrets.NORWAY_MERCHANT_ID}}
          Credentials:1:Secret: ${{ secrets.NORWAY_MERCHANT_SECRET }}
          Credentials:2:MerchantId: ${{ secrets.FINNISH_MERCHANT_ID }}
          Credentials:2:Secret: ${{ secrets.FINNISH_MERCHANT_SECRET }}
          SampleWebsite:Url: https://localhost:5001

      - name: Commit Action Status
        if: ${{ always() }}
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          sha: ${{ steps.source-run-info.outputs.sourceHeadSha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Run Unit and UI tests
          conclusion: ${{ job.status }}
              
  publish_alpha_nuget:
    needs: [test-unit-ui]
    if: ${{ needs.test-unit-ui.outputs.sourceEvent != 'pull_request' && github.event.workflow_run.name == 'Dev' }}
    name: Publish alpha nuget
    runs-on: ubuntu-latest
    environment: ${{ github.event.workflow_run.name }}

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
    
      # - name: Publish test package to GitHub Package Registry
      #   run: dotnet nuget push "packages/*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --source  https://nuget.pkg.github.com/sveawebpay/index.json --skip-duplicate
  
  publish_sample_site:
    needs: [test-unit-ui]
    if: ${{ needs.test-unit-ui.outputs.sourceEvent != 'pull_request' }}  
    name: Publish sample site
    runs-on: ubuntu-latest
    environment: ${{ github.event.workflow_run.name }}

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
    
      # - name: 'Run Azure webapp deploy using publish profile credentials'
      #   uses: azure/webapps-deploy@v2
      #   with: 
      #     app-name: ${{ secrets.AZURE_WEBAPP_NAME }} # Replace with your app name
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_DEV_PUBLISH_PROFILE }} # Define secret variable in repository settings as per action documentation
      #     package: 'Sample.AspNetCore'